### ISSUE TITLE
[docs] Documentation of features

### ISSUE THREAD

**Issue by cyriltovena** [grafana/explore-logs#255]
Documentation on things like:
- Patterns: what are patterns and how should be used
- Service selections: what are services and how are they identified.
- Etc

**Comment by gtk-grafana** [comment]
Did we figure out how to get docs for this app in grafana.com?

**Comment by JStickler** [comment]
Closing because I think this issue was for the initial documentation for GA.

What are patterns documented here -> https://grafana.com/docs/grafana-cloud/visualizations/simplified-exploration/logs/patterns/

Services (labels and fields) documented here -> https://grafana.com/docs/grafana-cloud/visualizations/simplified-exploration/logs/labels-and-fields/
