### ISSUE TITLE
idea: Include/Exclude control

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#362]
A common thing we need to do is include or exclude (mutually exclusively) various items across the Explore Apps. We use a mix of language 'Add to filters', 'Include', 'Exclude'.

Proposal to make one control that we can later share, to provide a single way to do this. Ideally, it would look different to the 'Select' buttons to differentiate them from when users are drilling down.

![IMG_2740](https://github.com/grafana/explore-logs/assets/101659/0966ce91-bc96-4f7a-b2ae-4032cdd91e1e)

* Clicking 'Include' would highlight it visually
* Clicking 'Exclude' would turn off 'Include' and become highlighted instead (note that they are mutually exclusive)
* Clicking a selected item would de-select it (i.e. remove it from being included, or stop it from being excluded)
* Clicking the filter icon could reset it

### Questions

Do all apps support including, excluding, and reversing (undoing) that decision? If not, please explain here - the control may need to provide additional options.

**Comment by catherineymgui** [comment]
In Explore Metrics:
- Users select a value to Add to filters.
- Once selected, the bottom panel toggles back to show all labels. This is because we anticipate the users next step to be breaking down and viewing their metrics by other labels / values
- We don't currently support the ability to Exclude or Undo via the graph. I'm not totally against the idea, but I do agree with @/torkelo's concern on overlapping functionality with filters and if it's adding too much unnecessary UI complexity to a graph

**Comment by zizzpudding** [comment]
If we use that pattern, I suggest having just two buttons (like old style radio button on a car) push in to toggle on, push again to toggle off, push another one to toggle to that option). 
![radio](https://github.com/grafana/explore-logs/assets/573085/3d597a1e-a076-4635-a985-b3788703dd11)

**Comment by ivanahuckova** [comment]
Yes that's what we have in https://play.grafana.org/a/grafana-lokiexplore-app/explore?var-ds=ddhr3fttaw8aod&var-patterns=&var-lineFilter=&var-logsFormat=%20%7C%20logfmt&var-filters=service_name%7C%3D%7Ctempo-ingester&mode=service_details&actionView=patterns&var-labelBy=$__all&patterns=%5B%5D. Closing the issue as this was implemented and is used.
