### ISSUE TITLE
nit: low contrast is hard to read in dark mode

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#519]
- [ ] use `detected_level` label instead of `level`
- [ ] tweak colours

<img width="480" alt="image" src="https://github.com/grafana/explore-logs/assets/101659/74f5b191-b294-4177-8094-f529ecea5600">

**Comment by zizzpudding** [comment]
Text should either be max contrast dark (black) against a light background. 
![image](https://github.com/grafana/explore-logs/assets/573085/9078f076-4cd3-4242-b8ba-1f92b6ebaf7f)

**Comment by zizzpudding** [comment]
Contrast is bad on the other levels as well. We should run an accessibility check on this.

**Comment by zizzpudding** [comment]
![image](https://github.com/grafana/explore-logs/assets/573085/01aca39a-c2de-4145-847f-0370b5092949)

**Comment by gtk-grafana** [comment]
@zizzpudding How's this look?

<img width="585" alt="image" src="https://github.com/grafana/explore-logs/assets/109082771/9543c3db-e4e2-4642-b88b-f2edaeb333a7">
<img width="1700" alt="image" src="https://github.com/grafana/explore-logs/assets/109082771/26467878-baf5-47ff-b954-89e932f25e0b">

**Comment by gtk-grafana** [comment]
I couldn't use a real border because we already had one: 
<img width="470" alt="image" src="https://github.com/grafana/explore-logs/assets/109082771/96ad213f-ff7c-4eb6-a04c-a52789a13025">
If we're fine with the text being a bit more scrunched up, we could put the level color treatment on the bottom after all.

Thoughts?
