### ISSUE TITLE
Determining the parser can be incorrect

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/explore-logs#708]
Right now we only check the first log line, and assume that all logs returned by the current query return the same format.
We ideally need to check all of them, and set different parsing stages for json, logfmt, and mixed.

Might be solved by https://github.com/grafana/explore-logs/issues/678, or could be made more accurate by checking more then the first log line

**Comment by trevorwhitney** [comment]
Yes, this will be fixed by #678, we will return an [array of parsers](https://github.com/grafana/loki/blob/main/pkg/querier/querier.go#L1243), and we parse every line, so it will be a complete list of all parsers valid for that stream.

we should be able to apply all valid parsers as well in a single query, as long as we drop errors.

**Comment by gtk-grafana** [comment]
Fixed in https://github.com/grafana/explore-logs/issues/678
