### ISSUE TITLE
Logs panel: Share link to log line

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/explore-logs#772]
Allow users to share links to a specific log line within the logs panel.

**Comment by zizzpudding** [comment]
My concern about adding a button to the breadcrumb is that it might not be as discoverable as a button in the app. 
I like adding a toggle split button in the app (perhaps to the right of the Go to Explore) button. 

Users can click on the share to copy the long link to the clipboard and click on the drop down menu to select a short link instead.

Do you think we should default to short link? or long link?

**Comment by zizzpudding** [comment]
Going by what has been done in the past. it looks like the short link is the default. There are also 4 different flavors of sharing the link. 
Shortened with a date/time filter
Shortened without a date/time filter
Long with a date/time filter
Long without a date/time filter


I assume we want to default with the date/time filter as part of the URL. Especially if our main use case is sharing a log line(s) that was found. (not recreating the query for a different time frame). 

Here's a [quick screenshot of adding the button to the content ](https://www.figma.com/design/NT8kODiyLshr8S5WoXplIA/ExploreLogs?node-id=1808-5025&t=bCzjPFBOYUW3ribN-4)rather than adding to the breadcrumb. 

![Image](https://github.com/user-attachments/assets/14312045-dd4a-4491-a54e-4691a68378ec)

**Comment by gtk-grafana** [comment]
I don't think we want users to copy a link without a time range, and I don't understand why we would provide a way to copy the long URL, it's already there in the browser if folks don't want a short url for some reason
