### ISSUE TITLE
Detected fields: Use "type" to determine when to run avg_over_time queries

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/explore-logs#865]
Currently we're still using the hardcoded list of numeric fields instead of the detected_fields type.

We need to use the detected_field type of "duration", "bytes", "float" and run avg_over_time aggregations

**Comment by svennergr** [comment]
Types are according to https://github.com/grafana/loki/blob/1f9beae0cce4d3ca939bd54d7da0c27d79e0864a/pkg/querier-rf1/querier.go#L763

**Comment by lattaai1** [comment]
Hello, I tried to fix the issue

This is what I did:
I have updated the `buildFieldsQuery` function in the `fields.ts` file to use the detected field type for avg_over_time aggregations. Now, instead of using a hardcoded list of numeric fields, we check the detected field type and use the appropriate unwrap function for duration, bytes, and float fields. This change will make the query more dynamic and accurate based on the actual field types detected.

I also created pull request: https://github.com/grafana/explore-logs/pull/866


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
> 
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
