### ISSUE TITLE
Table: Infinite scroll breaking table summary and line counts

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/explore-logs#966]
On the `logsPanelQuery`, the series length is not being adjusted, but values are. This is causing the table count in the footer to show the wrong number:
<img width="1723" alt="Image" src="https://github.com/user-attachments/assets/8f0a187d-3f99-4fd3-a686-6392c84a4d6b" />

and the density calculations are wrong

<img width="440" alt="Image" src="https://github.com/user-attachments/assets/0ee63101-70e8-4621-a150-404692647024" />

<img width="733" alt="Image" src="https://github.com/user-attachments/assets/2fff4051-8c18-4e0f-9cc3-90b2d506fe35" />

CC: @matyax

**Comment by matyax** [comment]
Ack.

**Comment by matyax** [comment]
Oh, I see the problem. The thing is that the Logs Table doesn't have infinite scroll, and the infinite scroll data is actually encapsulated in the LogsPanel, in PanelData, which is what gets passed to the rows: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/logs/LogsPanel.tsx#L377

![Image](https://github.com/user-attachments/assets/d8a0921c-91ad-4057-93ad-3663c0a23771)

The problem is that 1) the new results are never updated in the Scene state and 2) what the table is actually seeing, unfortunately, is the original data frame with mutated fields 😬 .

I think we should fix those 2, ideally.
